### ISSUE TITLE
Start porting Android to iOS devices using this.

### ISSUE THREAD

**Issue by upintheairsheep** [konradybcio/linux-apple#11]
See https://github.com/corellium/projectsandcastle for the code, use the  Linux-Apple to attempt to port Android with the more compatible kernel.

**Comment by upintheairsheep** [comment]
Porting Android's recovery and fastboot and TWRP as well would also be nice.

**Comment by konradybcio** [comment]
bold of you to assume that's not already underway :P 

there's a horrible bug that prevents it from running on a7 and maybe a8 (at least for now) and it makes more sense to focus on getting the kernel drivers ready first - otherwise it's gonna be useless anyway

**Comment by upintheairsheep** [comment]
> bold of you to assume that's not already underway :P
> 
> there's a horrible bug that prevents it from running on a7 and maybe a8 (at least for now) and it makes more sense to focus on getting the kernel drivers ready first - otherwise it's gonna be useless anyway

Yep. I’m more aiming towards A10 iPad models.

**Comment by konradybcio** [comment]
closing for now as this is not a kernel issue

feel free to reopen this on https://github.com/SoMainline/linux-apple-resources
