### ISSUE TITLE
Won't boot up on A7.

### ISSUE THREAD

**Issue by haxio** [konradybcio/linux-apple#3]
I did everything right, I am sure. but when I try to boot up linux on my device (A7), it gives the "Failed to delete bootargs" error, then "Booting Linux" and, nothing.

**Comment by konradybcio** [comment]
try building new pongo and new linux, i changed a couple of things

also make sure you have `CONFIG_*_APPLE`, `CONFIG_FB_SIMPLE` and `CONFIG_USB_DWC2` enabled

**Comment by onny** [comment]
> Already worked! Thanks. ❤️

If you got your device booting you might want to document it in the postmarketOS wiki :) https://wiki.postmarketos.org/wiki/Main_Page

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@haxio, have you considered doing what @onny mentioned?
