### ISSUE TITLE
Beginner Guide to use this for iPad Linux installation

### ISSUE THREAD

**Issue by kwccoin** [konradybcio/linux-apple#5]
Newbie question

From https://news.ycombinator.com/item?id=31679293
to https://konradybcio.pl/linuxona7/

I can do the pongos, well, just do make all.  

May I ask, sorry but as a newbie, what is the instruction to do this linux-apple here from macOS.

**Comment by asdfugil** [comment]
https://github.com/SoMainline/linux-apple-resources

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@konradybcio and @asdfugil, I suggest that that be added to https://github.com/konradybcio/linux-apple/blob/apple/v5.19-rc1/README.
