### ISSUE TITLE
Fails to boot on iPhone 8 (A11)

### ISSUE THREAD

**Issue by AntarcticanWaffles** [konradybcio/linux-apple#6]
The pongoOS shell gets to "Booting Linux..." but eventually goes black and boots into iOS.
The shell mentions
```
Device tree for D20 not found.
failed to apply overlay to fdt
```
![checkra1n](https://user-images.githubusercontent.com/53932921/175919140-d824cb87-4ecb-4792-9068-38476e386456.jpg)

**Comment by foxlet** [comment]
You need to make sure `t8015-d20.dtb` is actually included in your dtbpack.

**Comment by konradybcio** [comment]
please check the apple/wip branch, i set up a CI there, you can click the green checkmark on the latest commit and download Image.lzma-16k and dtbpack

**Comment by AntarcticanWaffles** [comment]
Thanks, I got the phone booting now :-)
