### ISSUE TITLE
Framebuffer is broken on D211 (iPhone 8 Plus)

### ISSUE THREAD

**Issue by foxlet** [konradybcio/linux-apple#7]
As stated in the title. This issue is more relevant to the pongoOS fork, but I've posted it here for visibility.

![Screenshot_20220630_040909](https://user-images.githubusercontent.com/1627533/176628834-c1807cb7-8b89-4566-a4e9-e0fbf2f5673d.png)

**Comment by konradybcio** [comment]
just noting that this was fixed in a pongoos pull

https://github.com/konradybcio/pongoOS/commit/fcfd41f437196100a38e7ac84841b527476f9a81

**Comment by asdfugil** [comment]
iphone 8 isn't iphone 8 plus
