### ISSUE TITLE
Framebuffer broken on J207

### ISSUE THREAD

**Issue by alfiecg24** [konradybcio/linux-apple#8]
I've booted Linux but the framebuffer does not appear correct.

![image](https://user-images.githubusercontent.com/63724031/184401303-590de132-8464-4fb9-87f6-81e6253d4d31.jpeg)

The above is using the regular branch.

![image](https://user-images.githubusercontent.com/63724031/184402026-27607c53-18b7-4968-b0bc-55eb35fa9693.jpeg)

The above is using the apple-test branch.

**Comment by asdfugil** [comment]
this is due to the framebuffer having the wrong width, could you please try this pongoOS? https://cdn.discordapp.com/attachments/672628720497852459/1008624183288283166/Pongo.bin

**Comment by alfiecg24** [comment]
> 
> 
> could you please try this pongoOS? https://cdn.discordapp.com/attachments/672628720497852459/1008624183288283166/Pongo.bin

![image](https://user-images.githubusercontent.com/63724031/184612363-ace09175-1263-4a37-9333-0752d7f7b0ef.jpeg)

This is the result - it's an improvement but still not not correct width. Thanks for your help! Do you have the source for that alternate .bin so I can have a look by any chance?

**Comment by asdfugil** [comment]
> > could you please try this pongoOS? https://cdn.discordapp.com/attachments/672628720497852459/1008624183288283166/Pongo.bin
> 
> ![image](https://user-images.githubusercontent.com/63724031/184612363-ace09175-1263-4a37-9333-0752d7f7b0ef.jpeg)
> 
> This is the result - it's an improvement but still not not correct width. Thanks for your help! Do you have the source for that alternate .bin so I can have a look by any chance?

You see, on some devices the framebuffer width as reported by iboot is slightly off, so it needs to be offseted
In the particular bin:

```diff
diff --git a/src/modules/linux/linux.c b/src/modules/linux/linux.c
index b6f3398..de9c8d0 100644
--- a/src/modules/linux/linux.c
+++ b/src/modules/linux/linux.c
@@ -99,11 +99,13 @@ int linux_dtree_overlay(char *boot_args)
     if (!strcmp(key, "N61") || // 6
         !strcmp(key, "N71") || !strcmp(key, "N71m") || // 6S
         !strcmp(key, "D10") || !strcmp(key, "D101") || // 7
-        !strcmp(key, "D20") || !strcmp(key, "D201"))   // 8
+        !strcmp(key, "D20") || !strcmp(key, "D201")) // 8
         width = gBootArgs->Video.v_width + 2;
-    else if (!strcmp(key, "N56") || // 6 Plus
-             !strcmp(key, "N66") || !strcmp(key, "N66m") || // 6S Plus
-             !strcmp(key, "D11") || !strcmp(key, "D111"))   // 7 Plus
+    else if (!strcmp(key, "N56")  || // 6 Plus
+             !strcmp(key, "N66")  || !strcmp(key, "N66m") || // 6S Plus
+             !strcmp(key, "D11")  || !strcmp(key, "D111") || // 7 Plus
+             !strcmp(key, "D211") || !strcmp(key, "D21")  || // 8 Plus
+             !strcmp(key, "J207") || !strcmp(key, "J208")) // iPad Pro (10.5-inch)
         width = gBootArgs->Video.v_width + 8;
     else if (!strcmp(key, "D22") || !strcmp(key, "D221")) { // X
         width = gBootArgs->Video.v_width + 11;
```
this makes it so that width is increased by 8 which still isn't enough appearently

**Comment by asdfugil** [comment]
This pongoOS increase the width by 11, it is a guessing game so please try it: https://cdn.discordapp.com/attachments/672628720497852459/1008675120698634250/Pongo.bin

**Comment by alfiecg24** [comment]
![image](https://user-images.githubusercontent.com/63724031/184623779-d59356ba-2228-49a6-963f-868ef77c67e7.jpeg)

Excellent improvement. Do you have one that increases it by 13? I think that would fix it!

**Comment by alfiecg24** [comment]
On a sidenote, I have copied that code into my pongoOS fork and built it, but running on device does not produce a different output to if I never changed the width at all. Any idea why this is? diff says that the file is different to the one I duplicated before I built the project again.

**Comment by alfiecg24** [comment]
Don't worry, I've managed to get my fork to work so for now I'll test out the different values to Gert the right one. Thank you so much for your help!

**Comment by asdfugil** [comment]
please do mention the correct offset afterwards though

**Comment by alfiecg24** [comment]
![image](https://user-images.githubusercontent.com/63724031/184625835-7cdaf94f-d344-410d-8f3d-56993e7286c8.jpeg)

This is adding 14 to the width

![image](https://user-images.githubusercontent.com/63724031/184625877-61fbcd9f-21e4-4266-8a0f-b268d3d43c65.jpeg)

This is adding 13 to the width!

It seems there's no right answer 🥴. Any ideas?

**Comment by alfiecg24** [comment]
![image](https://user-images.githubusercontent.com/63724031/184625835-7cdaf94f-d344-410d-8f3d-56993e7286c8.jpeg)

This is adding 14 to the width

![image](https://user-images.githubusercontent.com/63724031/184625877-61fbcd9f-21e4-4266-8a0f-b268d3d43c65.jpeg)

This is adding 13 to the width

It seems there's no right answer! Any ideas?

**Comment by asdfugil** [comment]
12

**Comment by asdfugil** [comment]
If you compare the photos it is evident that 13 is too much (it tilts to the other side)

**Comment by alfiecg24** [comment]
Perfect, thanks
