### ISSUE TITLE
Rename your project

### ISSUE THREAD

**Issue by upintheairsheep** [konradybcio/linux-apple#9]
Please rename your project to something unique to avoid confusion with ashahi and because it’s too generic

**Comment by konradybcio** [comment]
almost every fork of linux on github is named 'linux' and nobody complains about confusing it with kernel.org

on a more serious note, I really don't think this is much of an issue.. this repo is only meant for developers and not end users for now anyway (unless your end user is happy with just framebuffer and usb)
